const path = require("node:path");
const net = require("node:net");
const fs = require("node:fs");
const { app, BrowserWindow, shell, session } = require("electron");

const isPackaged = app.isPackaged;
const appRoot = isPackaged ? process.resourcesPath : path.resolve(__dirname, "..");

process.env.NODE_ENV = "production";
process.env.MOTIONXAMON_APP_ROOT = appRoot;

let mainWindow;
let logFile;
let instagramLoginWindow;

const singleInstanceLock = app.requestSingleInstanceLock();
if (!singleInstanceLock) {
  app.quit();
}

function log(message) {
  try {
    if (!logFile) return;
    fs.appendFileSync(logFile, `[${new Date().toISOString()}] ${message}\n`, "utf8");
  } catch {
    // Ignore logging failures.
  }
}

function findFreePort() {
  return new Promise((resolve, reject) => {
    const server = net.createServer();
    server.on("error", reject);
    server.listen(0, "127.0.0.1", () => {
      const address = server.address();
      const port = typeof address === "object" && address ? address.port : 4117;
      server.close(() => resolve(port));
    });
  });
}

function startServer() {
  log(`starting server on port ${process.env.PORT}`);
  require(path.join(appRoot, "dist", "server.cjs"));
}

function cookieToNetscapeLine(cookie) {
  const domain = cookie.domain || "";
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const pathValue = cookie.path || "/";
  const secure = cookie.secure ? "TRUE" : "FALSE";
  const expiry = cookie.session ? "0" : String(Math.trunc(cookie.expirationDate || Date.now() / 1000));
  return [domain, includeSubdomains, pathValue, secure, expiry, cookie.name, cookie.value].join("\t");
}

async function saveInstagramCookies(instagramSession) {
  const cookies = (await instagramSession.cookies.get({}))
    .filter((cookie) => /(^|\.)instagram\.com$/i.test(cookie.domain || ""))
    .sort((a, b) => `${a.domain}${a.path}${a.name}`.localeCompare(`${b.domain}${b.path}${b.name}`));

  const hasSession = cookies.some((cookie) => cookie.name === "sessionid");
  if (!hasSession) return "";

  const filePath = path.join(app.getPath("userData"), "instagram-cookies.txt");
  const content = [
    "# Netscape HTTP Cookie File",
    "# Generated by motionxamon. Keep this file private.",
    ...cookies.map(cookieToNetscapeLine),
    ""
  ].join("\n");

  fs.writeFileSync(filePath, content, "utf8");
  return filePath;
}

global.motionxamonConnectInstagram = function connectInstagram() {
  return new Promise((resolve, reject) => {
    const instagramSession = session.fromPartition("persist:motionxamon-instagram");
    let settled = false;

    const finish = (result) => {
      if (settled) return;
      settled = true;
      resolve(result);
      if (instagramLoginWindow && !instagramLoginWindow.isDestroyed()) {
        instagramLoginWindow.close();
      }
      instagramLoginWindow = undefined;
    };

    instagramLoginWindow = new BrowserWindow({
      width: 520,
      height: 760,
      minWidth: 420,
      minHeight: 620,
      backgroundColor: "#0A0B0E",
      title: "Connect Instagram",
      icon: path.join(appRoot, "build", "icon.ico"),
      autoHideMenuBar: true,
      parent: mainWindow || undefined,
      webPreferences: {
        partition: "persist:motionxamon-instagram",
        nodeIntegration: false,
        contextIsolation: true
      }
    });

    const checkCookies = async () => {
      try {
        const cookiesFile = await saveInstagramCookies(instagramSession);
        if (cookiesFile) {
          finish({ ok: true, cookiesFile });
        }
      } catch (error) {
        reject(error);
      }
    };

    instagramLoginWindow.webContents.on("did-finish-load", checkCookies);
    instagramLoginWindow.webContents.on("did-navigate", checkCookies);
    instagramLoginWindow.webContents.on("did-navigate-in-page", checkCookies);
    instagramSession.cookies.on("changed", checkCookies);
    instagramLoginWindow.on("closed", async () => {
      instagramLoginWindow = undefined;
      instagramSession.cookies.off("changed", checkCookies);
      try {
        const cookiesFile = await saveInstagramCookies(instagramSession);
        finish(cookiesFile ? { ok: true, cookiesFile } : { ok: false, error: "Instagram login was not completed." });
      } catch (error) {
        reject(error);
      }
    });

    instagramLoginWindow.loadURL("https://www.instagram.com/accounts/login/");
  });
};

global.motionxamonClearInstagram = async function clearInstagram() {
  const instagramSession = session.fromPartition("persist:motionxamon-instagram");
  await instagramSession.clearStorageData({
    storages: ["cookies", "localstorage", "indexdb", "cachestorage", "serviceworkers"]
  });

  const filePath = path.join(app.getPath("userData"), "instagram-cookies.txt");
  try {
    fs.rmSync(filePath, { force: true });
  } catch {
    // Ignore cleanup failures; the server also clears settings state.
  }

  return { ok: true };
};

function createWindow() {
  const isMac = process.platform === "darwin";

  mainWindow = new BrowserWindow({
    width: 1180,
    height: 820,
    minWidth: 940,
    minHeight: 680,
    backgroundColor: "#0A0B0E",
    title: "motionxamon",
    icon: path.join(appRoot, "build", "icon.ico"),
    autoHideMenuBar: true,
    ...(isMac ? {
      titleBarStyle: "hiddenInset",
      trafficLightPosition: { x: 18, y: 18 },
      vibrancy: "under-window",
      visualEffectState: "active"
    } : {}),
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true
    }
  });

  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    shell.openExternal(url);
    return { action: "deny" };
  });

  mainWindow.loadURL(`http://127.0.0.1:${process.env.PORT}`);
}

app.on("second-instance", () => {
  if (!mainWindow) return;
  if (mainWindow.isMinimized()) mainWindow.restore();
  mainWindow.focus();
});

process.on("uncaughtException", (error) => {
  log(`uncaughtException: ${error.stack || error.message || error}`);
});

process.on("unhandledRejection", (error) => {
  log(`unhandledRejection: ${error && error.stack ? error.stack : error}`);
});

app.whenReady().then(async () => {
  app.setName("motionxamon");
  logFile = path.join(app.getPath("userData"), "motionxamon.log");
  process.env.MOTIONXAMON_DEFAULT_DOWNLOADS_DIR = path.join(app.getPath("downloads"), "motionxamon");
  process.env.MOTIONXAMON_TOOLS_DIR = path.join(app.getPath("userData"), "tools");
  process.env.PORT = String(await findFreePort());
  startServer();
  setTimeout(createWindow, 700);

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
